In [1]:
import numpy as np

In [2]:
X=np.array([[0,0],[0,1],[1,0],[1,1]])
Y=np.array([[0,0,0,1]]).T
print(X)
print(Y)
X.shape,Y.shape

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[[0]
 [0]
 [0]
 [1]]


((4, 2), (4, 1))

In [3]:
def sig(z):
    return 1/(1+np.exp(-z))

In [4]:
def derivativeSig(z):
    return sig(z)*(1-sig(z))

In [5]:
#Forward propagation without hidden layer
weights=2*np.random.random((2,1))-1
bias=2*np.random.random(1)-1
lr=0.01
weights,bias

(array([[-0.6395922 ],
        [ 0.11071311]]), array([-0.10918162]))

In [6]:
ip=X
op=sig(np.dot(ip,weights)+bias)
op

array([[0.47273168],
       [0.50038287],
       [0.32108854],
       [0.34568505]])

In [7]:
#Backward Propagation without hidden layer
for iter in range(100000):
    firstTerm=op-Y
    prevInputs=np.dot(ip,weights)+bias
    secondTerm=derivativeSig(prevInputs)
    firstsecond=firstTerm*secondTerm

    changes=np.array([[0.0],[0.0]])
    for i in range(2):
        for j in range(4):
            changes[i][0]+=firstsecond[j][0]*ip[j][i]
    changes
    weights=weights-lr*changes

    biasChange=0.0
    for j in range(4):
        biasChange+=firstsecond[j][0]*1
    bias=bias-lr*biasChange
output=sig(np.dot(X,weights)+bias)
bias,weights
print(output)

[[2.15728416e-06]
 [1.07101299e-02]
 [1.68494083e-02]
 [9.88506507e-01]]


In [12]:
#Forward Propagation with hidden layer
wh=2*np.random.random((2,2))-1
bh=2*np.random.random((1,2))-1
wo=2*np.random.random((2,1))-1
bo=2*np.random.random((1,1))-1
lr=0.01
wh,bh,wo,bo

(array([[ 0.87729803,  0.79448094],
        [-0.24608636,  0.16596045]]),
 array([[-0.45474902, -0.73067582]]),
 array([[-0.19841806],
        [-0.11156674]]),
 array([[0.78568764]]))

In [13]:
op_input_layer=X
ip_hidden_layer=np.dot(op_input_layer,wh)+bh
op_hidden_layer=sig(ip_hidden_layer)
ip_output_layer=np.dot(op_hidden_layer,wo)+bo
op_output_layer=sig(ip_output_layer)
op_output_layer

array([[0.66203833],
       [0.66361564],
       [0.6475443 ],
       [0.64921354]])

In [17]:
#Back Propagation with hidden layer
for iter in range(100000):
    op_input_layer=X
    ip_hidden_layer=np.dot(op_input_layer,wh)+bh
    op_hidden_layer=sig(ip_hidden_layer)
    ip_output_layer=np.dot(op_hidden_layer,wo)+bo
    op_output_layer=sig(ip_output_layer)
    op_output_layer
    firstTerm_output_layer=op_output_layer-Y
    secondTerm_output_layer=derivativeSig(ip_output_layer)
    firsttwo_output_layer=firstTerm_output_layer*secondTerm_output_layer

    firstTerm_hidden_layer=np.dot(firsttwo_output_layer,wo.T)
    secondTerm_hidden_layer=derivativeSig(ip_hidden_layer)
    firsttwo_hidden_layer=firstTerm_hidden_layer*secondTerm_hidden_layer

    changes_output_layer=np.dot(op_hidden_layer.T,firsttwo_output_layer)
    changes_bias_output_layer=np.sum(firsttwo_output_layer, axis=0, keepdims=True)

    changes_hidden_layer=np.dot(op_input_layer.T,firsttwo_hidden_layer)
    changes_bias_hidden_layer=np.sum(firsttwo_hidden_layer, axis=0, keepdims=True)

    wo=wo-lr*changes_output_layer
    bo=bo-lr*changes_bias_output_layer

    wh=wh-lr*changes_hidden_layer
    bh=bh-lr*changes_bias_hidden_layer

op_input_layer=X
ip_hidden_layer=np.dot(op_input_layer,wh)+bh
op_hidden_layer=sig(ip_hidden_layer)
ip_output_layer=np.dot(op_hidden_layer,wo)+bo
op_output_layer=sig(ip_output_layer)
op_output_layer

array([[7.26544505e-04],
       [1.60006764e-02],
       [1.62512862e-02],
       [9.76415505e-01]])